name: Hello World CI/CD

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  hello-world-job:
    runs-on: ubuntu-latest # Specifies the type of runner to use

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3 # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Run a one-line script
        run: echo "Hello, world!" # Executes a simple command

      - name: Run a multi-line script
        run: |
          echo "This is a multi-line script."
          echo "It can execute multiple commands."
